### ISSUE TITLE
Build steps for UbuntuVM

### ISSUE THREAD

**Issue by martynp** [daniestevez/grcon2020-workshop#1] opened 2020-09-14 09:50 UTC
For those using the 'provided' UbuntuVM, this steps should get everything (I think!)

- `sudo apt-get install swig liborc-0.4`

- `cd ~ && mkdir deps`

- `cd ~/deps`
- `git clone https://github.com/daniestevez/gr-satellites.git -b v3.4.0`
- `cd gr-satellites && mkdir build && cd build`
- `cmake ../ && make && sudo make install && sudo ldconfig`

- `cd ~/deps`
- `git clone https://github.com/daniestevez/gr-dslwp.git -b maint38`
- `cd gr-dslwp && mkdir build && cd build`
- `cmake ../ && make && sudo make install && sudo ldconfig`

- `pip3 install jupyter`
- `pip3 install construct`

**Comment by daniestevez** [comment] 2020-09-14 10:40
Thanks! I'll  linki these instructions in the README.

Probably I will upload in a while a new OVA image with all this installed.

**Comment by daniestevez** [comment] 2020-09-14 11:09
I have just added to the README the link with the OVA image with the requirements already installed.

**Comment by daniestevez** [comment] 2022-03-28 20:31
Closing this, since the issue is already linked in the README.

**Closed as completed by daniestevez** 2022-03-28 20:31 UTC
